13 many target qubits automatic swapping
DATX11-22/Quaru pull request #22
Opened 2023-02-24 00:37 UTC by guskal01

2023-02-24 10:38 UTC, BAMF0 requested changes
Looks good, but there should be swap tests in order to validate the functionality.

2023-02-24 10:45 UTC, simonengstrm requested changes
There are a couple of places where I would appreciate some more documentation. Other than this and some more tests with swapping it looks good.

2023-02-24 10:45 UTC, simonengstrm commented on src/register.rs
> +                j |= ((i >> k) & 1) << perm[k];
I think this code should be commented more. It is very hard to read and understand what it does other than that it permutes the qubits according to perm.

2023-02-24 10:45 UTC, simonengstrm commented on src/register.rs
> +        // Permutation which the qubits will be shuffled according to
Unfinished docs?

2023-02-28 14:00 UTC, BAMF0 approved these changes
Looks good

2023-02-28 14:26 UTC, BAMF0 commented
I merge
 now

2023-02-28 14:27 UTC, merged