29 add from state
DATX11-22/quaru pull request #54
Opened 2023-03-24 12:26 UTC by JonatanMentzer

Resolves #29 

from_state or new_qubits as it is called in the code can create any state of valid qubits.

2023-03-24 13:16 UTC, simonengstrm requested changes
Looks good! Would be nice with some more docs in a couple of places.
Also maybe squash commit message history when merging

2023-03-24 13:16 UTC, simonengstrm commented on src/register.rs
> +    pub fn try_new_qubits(input_bits: &[Array2<Complex<f64>>]) -> Result<Self, OperationError> {
Would be nice to have some documentation of this function

2023-03-24 13:16 UTC, simonengstrm commented on src/register.rs
> +    /// Checks if input qubit has total probability 1
Add docs note about parameter/return?

2023-03-24 13:16 UTC, simonengstrm commented on src/register.rs
> +    /// Checks that input qubit is correct
Add docs note about parameter/return?

2023-03-27 08:35 UTC, BAMF0 commented
We should make sure to keep commits in imperative form to be consistent!

2023-03-27 08:37 UTC, BAMF0 reviewed
I agree with the changes as requested by @simonengstrm

2023-03-29 09:23 UTC, JonatanMentzer commented
Will squash and merge after PR is accepted.

2023-03-29 09:26 UTC, simonengstrm approved these changes
lgtm!

2023-03-29 09:27 UTC, merged