55 add openqasm support
DATX11-22/quaru pull request #59
Opened 2023-03-28 09:47 UTC by edvinsternvik

Implementes support for running openqasm files using
```
use quaru::openqasm;
let registers = openqasm::run_openqasm(Path::new("filepath.qasm"));
```

which returns the quantum and classical registers defined in the .qasm program (Or an error).
Supports most of the language with a few exceptions:
* Opaque gates are gates whose definition is not specified in the program. This could be useful if a gate is difficult to describe in the language, but is physically realizable. However, since the definition is not specified it is obviously impossible to simulate their behavior. An error is returned when a program is ran which contain these types of gates.
* In openqasm you can define multiple quantum registers and run a CX gate with the control bit from one register and the target bit from another registers. Due to how the simulator is implemented it is impossible to apply a gate with targets in different register. An error is returned when a program is ran which contain these types of operations.

2023-03-28 11:32 UTC, BAMF0 reviewed
looks good!

2023-03-28 12:08 UTC, simonengstrm requested changes
Great! Just one comment

2023-03-29 12:36 UTC, edvinsternvik commented on src/operation.rs
> +use num::complex::Complex64;
Fixed by 4ca3103df11a8ce90ae11adac65c6944a677a959

2023-03-30 12:52 UTC, simonengstrm approved these changes

2023-03-30 13:11 UTC, merged